const sampledata=[
  {
    University: "Manhattan",
    Program: "Phd",
    Degree:"Economics",
    Season:"Winter Fall",
    Status:"Waitlisted",
    Date:26/1/2005,
    Email: "abcd@gmail.com",
    GPA:4.2,
    General_GRE:3.2,
    Verbal_GRE:3.7,
    Aw_GRE:3.3,
  },
  {
    University: "Oxford",
    Program: "Phd",
    Degree:"Physics",
    Season:"Summer",
    Status:"Shortlisted",
    Date:26/1/2025,
    Email:"oxymoron@gmail.com",
    GPA:4.3,
    General_GRE:3.1,
    Verbal_GRE:3.5,
    Aw_GRE:3.8,
  },
  {
    University: "Manhattan",
    Program: "Master's",
    Degree:"Political Science",
    Season:"Summer Fall",
    Status:"Shortlisted",
    Date:26/1/2005,
    Email: "ad@gmail.com",
    GPA:4.5,
    General_GRE:2.2,
    Verbal_GRE:4.7,
    Aw_GRE:3.3,
  },{
    University: "Harvard",
    Program: "PhD",
    Degree: "Computer Science",
    Season: "Fall",
    Status: "Accepted",
    Date: 15/12/2024,
    Email: "cs.harvard@app.com",
    GPA: 4.0,
    General_GRE: 3.6,
    Verbal_GRE: 3.9,
    Aw_GRE: 4.0,
  },
  {
    University: "Stanford",
    Program: "Master's",
    Degree: "Data Science",
    Season: "Spring",
    Status: "Rejected",
    Date: 15/12/2024,
    Email: "ds.stan@app.com",
    GPA: 3.9,
    General_GRE: 3.4,
    Verbal_GRE: 3.2,
    Aw_GRE: 3.6,
  },
  {
    University: "Cambridge",
    Program: "PhD",
    Degree: "Philosophy",
    Season: "Winter",
    Status: "Waitlisted",
    Date: 15/12/2024,
    Email: "philosophy@cam.uk",
    GPA: 4.1,
    General_GRE: 3.3,
    Verbal_GRE: 4.0,
    Aw_GRE: 3.7,
  },
  {
    University: "Yale",
    Program: "Master's",
    Degree: "Law",
    Season: "Fall",
    Status: "Shortlisted",
    Date: 15/12/2024,    Email: "law.yale@app.com",
    GPA: 3.8,
    General_GRE: 3.0,
    Verbal_GRE: 3.7,
    Aw_GRE: 3.4,
  },
  {
    University: "Columbia",
    Program: "PhD",
    Degree: "Psychology",
    Season: "Spring",
    Status: "Rejected",
    Date: 15/12/2024,    Email: "psy.columbia@edu.com",
    GPA: 3.7,
    General_GRE: 2.8,
    Verbal_GRE: 3.3,
    Aw_GRE: 3.0,
  },
  {
    University: "Berkeley",
    Program: "PhD",
    Degree: "Mathematics",
    Season: "Fall",
    Status: "Accepted",
    Date: 15/12/2024,    Email: "math.berk@uni.com",
    GPA: 4.4,
    General_GRE: 3.9,
    Verbal_GRE: 3.8,
    Aw_GRE: 3.9,
  },
  {
    University: "Princeton",
    Program: "Master's",
    Degree: "Econometrics",
    Season: "Winter",
    Status: "Shortlisted",
    Date: 15/12/2024,    Email: "econo@princeton.com",
    GPA: 4.6,
    General_GRE: 3.7,
    Verbal_GRE: 4.1,
    Aw_GRE: 4.0,
  },
  {
    University: "MIT",
    Program: "PhD",
    Degree: "Artificial Intelligence",
    Season: "Summer",
    Status: "Accepted",
    Date: 15/12/2024,    Email: "ai@mit.edu",
    GPA: 4.9,
    General_GRE: 4.0,
    Verbal_GRE: 3.9,
    Aw_GRE: 4.2,
  },
  {
    University: "UCLA",
    Program: "Master's",
    Degree: "Business Analytics",
    Season: "Fall",
    Status: "Waitlisted",
    Date: 15/12/2024,    Email: "ba.ucla@gmail.com",
    GPA: 3.85,
    General_GRE: 3.5,
    Verbal_GRE: 3.6,
    Aw_GRE: 3.4,
  },
  {
    University: "Toronto",
    Program: "PhD",
    Degree: "Neuroscience",
    Season: "Winter",
    Status: "Shortlisted",
    Date: 15/12/2024,    Email: "neuro@utoronto.ca",
    GPA: 4.3,
    General_GRE: 3.6,
    Verbal_GRE: 3.8,
    Aw_GRE: 3.5,
  },
  {
    University: "Edinburgh",
    Program: "Master's",
    Degree: "International Relations",
    Season: "Summer",
    Status: "Rejected",
    Date: 15/12/2024,    Email: "ir.edin@uk.com",
    GPA: 3.6,
    General_GRE: 2.9,
    Verbal_GRE: 3.1,
    Aw_GRE: 2.8,
  }

];

module.exports = { data: sampledata };